# Generated by Django 4.2.29 on 2026-04-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalsBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'globals_batch',
            },
        ),
        migrations.CreateModel(
            name='GlobalsDepartmentinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'globals_departmentinfo',
            },
        ),
        migrations.CreateModel(
            name='GlobalsDesignation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'globals_designation',
            },
        ),
        migrations.CreateModel(
            name='GlobalsExtrainfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='student', max_length=20)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='system_admin.globalsdepartmentinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrainfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'globals_extrainfo',
            },
        ),
        migrations.CreateModel(
            name='GlobalsProgramme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='system_admin.globalsdepartmentinfo')),
            ],
            options={
                'db_table': 'globals_programme',
            },
        ),
        migrations.CreateModel(
            name='UserRoleSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('switched_at', models.DateTimeField(auto_now=True)),
                ('session_data', models.JSONField(default=dict)),
                ('active_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsdesignation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_role_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_admin_user_role_session',
            },
        ),
        migrations.CreateModel(
            name='GlobalsStudentinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], default='GEN', max_length=10)),
                ('semester', models.CharField(blank=True, max_length=10, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hall_no', models.IntegerField(blank=True, null=True)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsbatch')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsprogramme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_studentinfo',
            },
        ),
        migrations.CreateModel(
            name='GlobalsStaffinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsdepartmentinfo')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsdesignation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_staffinfo',
            },
        ),
        migrations.CreateModel(
            name='GlobalsHoldsDesignation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('working', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='system_admin.globalsdesignation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_holdsdesignation',
            },
        ),
        migrations.CreateModel(
            name='GlobalsFacultyinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsdepartmentinfo')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.globalsdesignation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_info', to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_facultyinfo',
            },
        ),
        migrations.AddField(
            model_name='globalsbatch',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='system_admin.globalsdepartmentinfo'),
        ),
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_name', models.CharField(max_length=100)),
                ('approver_designation', models.CharField(max_length=100)),
                ('justification', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_admin_emergency_access_log',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_archived', 'User Archived'), ('role_assigned', 'Role Assigned'), ('role_reassigned', 'Role Reassigned'), ('role_revoked', 'Role Revoked'), ('password_reset', 'Password Reset'), ('bulk_import', 'Bulk Import'), ('emergency_access', 'Emergency Access Granted'), ('role_switched', 'Role Switched'), ('module_access', 'Module Access')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_admin_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedUserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_user_id', models.IntegerField()),
                ('user_data', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField()),
                ('retention_until', models.DateField()),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_admin_archived_user_data',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleConflictMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_with', to='system_admin.globalsdesignation')),
                ('role2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_also', to='system_admin.globalsdesignation')),
            ],
            options={
                'db_table': 'system_admin_role_conflict_matrix',
                'unique_together': {('role1', 'role2')},
            },
        ),
    ]
