# Generated by Django 4.2.29 on 2026-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_archived', 'User Archived'), ('role_assigned', 'Role Assigned'), ('role_reassigned', 'Role Reassigned'), ('role_revoked', 'Role Revoked'), ('password_reset', 'Password Reset'), ('bulk_import', 'Bulk Import'), ('emergency_access', 'Emergency Access Granted'), ('role_switched', 'Role Switched'), ('module_access', 'Module Access'), ('department_head_assigned', 'Department Head Assigned')], max_length=50),
        ),
    ]
