# Generated by Django 4.2.29 on 2026-04-21 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0003_designation_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('running_batch', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programme_curriculum_batch',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('working_curriculum', models.BooleanField(default=True)),
                ('no_of_semester', models.PositiveIntegerField(default=1)),
                ('min_credit', models.PositiveIntegerField(default=0)),
                ('latest_version', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programme_curriculum_curriculum',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'programme_curriculum_discipline',
            },
        ),
        migrations.CreateModel(
            name='GlobalsFaculty',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_faculty',
            },
        ),
        migrations.CreateModel(
            name='GlobalsModuleaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=155)),
                ('program_and_curriculum', models.BooleanField()),
                ('course_registration', models.BooleanField()),
                ('course_management', models.BooleanField()),
                ('other_academics', models.BooleanField()),
                ('spacs', models.BooleanField()),
                ('department', models.BooleanField()),
                ('examinations', models.BooleanField()),
                ('hr', models.BooleanField()),
                ('iwd', models.BooleanField()),
                ('complaint_management', models.BooleanField()),
                ('fts', models.BooleanField()),
                ('purchase_and_store', models.BooleanField()),
                ('rspc', models.BooleanField()),
                ('hostel_management', models.BooleanField()),
                ('mess_management', models.BooleanField()),
                ('gymkhana', models.BooleanField()),
                ('placement_cell', models.BooleanField()),
                ('visitor_hostel', models.BooleanField()),
                ('phc', models.BooleanField()),
                ('inventory_management', models.BooleanField()),
            ],
            options={
                'db_table': 'globals_moduleaccess',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('programme_begin_year', models.PositiveIntegerField(default=2026)),
            ],
            options={
                'db_table': 'programme_curriculum_programme',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system_admin.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system_admin.globalsextrainfo')),
                ('programme', models.CharField(max_length=10)),
                ('batch', models.IntegerField(default=2016)),
                ('cpi', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], max_length=10)),
                ('father_name', models.CharField(default='', max_length=40, null=True)),
                ('mother_name', models.CharField(default='', max_length=40, null=True)),
                ('hall_no', models.IntegerField(default=0)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(default='', max_length=40, null=True)),
                ('curr_semester_no', models.IntegerField(default=1)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.batch')),
            ],
            options={
                'db_table': 'academic_information_student',
            },
        ),
        migrations.RemoveField(
            model_name='globalsfacultyinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='globalsfacultyinfo',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='globalsfacultyinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='globalsprogramme',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='globalsstaffinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='globalsstaffinfo',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='globalsstaffinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='globalsstudentinfo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='globalsstudentinfo',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='globalsstudentinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='globalsdepartmentinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='globalsdesignation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='globalsdesignation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='globalsdesignation',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsdesignation',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='globalsdesignation',
            name='dept_if_not_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.globalsdepartmentinfo'),
        ),
        migrations.AddField(
            model_name='globalsdesignation',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsdesignation',
            name='type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='globalsholdsdesignation',
            name='held_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='globalsdepartmentinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalsdesignation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalsdesignation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.globalsdepartmentinfo'),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalsextrainfo',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='globalsholdsdesignation',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designees', to='system_admin.globalsdesignation'),
        ),
        migrations.AlterField(
            model_name='globalsholdsdesignation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalsholdsdesignation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds_designations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsholdsdesignation',
            name='working',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_designation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='globalsholdsdesignation',
            unique_together={('user', 'designation'), ('working', 'designation')},
        ),
        migrations.DeleteModel(
            name='GlobalsBatch',
        ),
        migrations.DeleteModel(
            name='GlobalsFacultyinfo',
        ),
        migrations.DeleteModel(
            name='GlobalsProgramme',
        ),
        migrations.DeleteModel(
            name='GlobalsStaffinfo',
        ),
        migrations.DeleteModel(
            name='GlobalsStudentinfo',
        ),
        migrations.AddField(
            model_name='discipline',
            name='programmes',
            field=models.ManyToManyField(blank=True, to='system_admin.programme'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.programme'),
        ),
        migrations.AddField(
            model_name='batch',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.curriculum'),
        ),
        migrations.AddField(
            model_name='batch',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_admin.discipline'),
        ),
        migrations.RemoveField(
            model_name='globalsholdsdesignation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='globalsholdsdesignation',
            name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'discipline', 'year')},
        ),
    ]
