# Generated by Django 4.2.29 on 2026-04-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_admin", "0004_batch_curriculum_discipline_globalsfaculty_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="requested_by",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_requests", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="requested_role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_requests", to="system_admin.globalsdesignation"),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="approved_role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_approvals", to="system_admin.globalsdesignation"),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="requested_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="requested_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="approved_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="approved_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("declined", "Declined"), ("revoked", "Revoked"), ("expired", "Expired")], default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="decision_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="emergencyaccesslog",
            name="hold",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_accesses", to="system_admin.globalsholdsdesignation"),
        ),
    ]
